title:   Prajwal Nagaraj
logo: /assets/img/Phead_circle.png
description: Business Analyst | Data Consultant | Data Analytics & Management Grad | Quality Engineer @ Accenture | Driving Data-Driven Solutions, Enhancing Quality Standards
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
